spring:
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 200000
      minimum-idle: 10
      maximum-pool-size: 20
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8087
  error:
    include-message: always

logging:
  level:
    org.springframework.security: debug
